chore: synchronising ci/cd, linting, nix, scripts

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,13 +5,10 @@ workflow:
       when: never
     - when: always
 
-default:
-  interruptible: true
-
 variables:
+  GIT_SUBMODULE_STRATEGY: recursive
   GH_PROJECT_PATH: "MatrixAI/${CI_PROJECT_NAME}"
   GH_PROJECT_URL: "https://${GITHUB_TOKEN}@github.com/${GH_PROJECT_PATH}.git"
-  GIT_SUBMODULE_STRATEGY: recursive
   # Cache .npm
   NPM_CONFIG_CACHE: "${CI_PROJECT_DIR}/tmp/npm"
   # Prefer offline node module installation
@@ -22,14 +19,25 @@ variables:
   # Homebrew cache only used by macos runner
   HOMEBREW_CACHE: "${CI_PROJECT_DIR}/tmp/Homebrew"
 
+default:
+  interruptible: true
+  before_script:
+    # Replace this in windows runners that use powershell
+    # with `mkdir -Force "$CI_PROJECT_DIR/tmp"`
+    - mkdir -p "$CI_PROJECT_DIR/tmp"
+
 # Cached directories shared between jobs & pipelines per-branch per-runner
 cache:
   key: $CI_COMMIT_REF_SLUG
+  # Preserve cache even if job fails
+  when: 'always'
   paths:
     - ./tmp/npm/
     - ./tmp/ts-node-cache/
     # Homebrew cache is only used by the macos runner
     - ./tmp/Homebrew
+    # Chocolatey cache is only used by the windows runner
+    - ./tmp/chocolatey/
     # `jest` cache is configured in jest.config.js
     - ./tmp/jest/
 
@@ -46,9 +54,10 @@ check:lint:
   needs: []
   script:
     - >
-        nix-shell --run '
-        npm run lint;
-        '
+      nix-shell --run '
+      npm run lint;
+      npm run lint-shell;
+      '
   rules:
     # Runs on feature and staging commits and ignores version commits
     - if: $CI_COMMIT_BRANCH =~ /^(?:feature.*|staging)$/ && $CI_COMMIT_TITLE !~ /^[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
@@ -76,11 +85,10 @@ check:test-generate:
   stage: check
   needs: []
   script:
-    - mkdir -p ./tmp
     - >
-        nix-shell --run '
-        ./scripts/check-test-generate.sh > ./tmp/check-test.yml
-        '
+      nix-shell --run '
+      ./scripts/check-test-generate.sh > ./tmp/check-test.yml
+      '
   artifacts:
     when: always
     paths:
@@ -118,20 +126,38 @@ build:merge:
     # Required for `gh pr create`
     - git remote add upstream "$GH_PROJECT_URL"
     - >
-        nix-shell -I nixpkgs=./pkgs.nix --packages gitAndTools.gh --run '
-        gh pr create \
-          --head staging \
-          --base master \
-          --title "ci: merge staging to master" \
-          --body "This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful." \
-          --assignee "@me" \
-          --no-maintainer-edit \
-          --repo "$GH_PROJECT_PATH" || true;
-        printf "Pipeline Attempt on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
-        | gh pr comment staging \
-          --body-file - \
-          --repo "$GH_PROJECT_PATH";
-        '
+      nix-shell --run '
+      gh pr create \
+        --head staging \
+        --base master \
+        --title "ci: merge staging to master" \
+        --body "This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful." \
+        --assignee "@me" \
+        --no-maintainer-edit \
+        --repo "$GH_PROJECT_PATH" || true;
+      printf "Pipeline Attempt on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
+      | gh pr comment staging \
+        --body-file - \
+        --repo "$GH_PROJECT_PATH";
+      '
+  rules:
+    # Runs on staging commits and ignores version commits
+    - if: $CI_COMMIT_BRANCH == 'staging' && $CI_COMMIT_TITLE !~ /^[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
+    # Runs on tag pipeline where the tag is a prerelease or release version
+    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
+
+build:dist:
+  stage: build
+  needs: []
+  script:
+    - >
+      nix-shell --run '
+      npm run build --verbose;
+      '
+  artifacts:
+    when: always
+    paths:
+      - ./dist
   rules:
     # Runs on staging commits and ignores version commits
     - if: $CI_COMMIT_BRANCH == 'staging' && $CI_COMMIT_TITLE !~ /^[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
@@ -142,11 +168,10 @@ build:platforms-generate:
   stage: build
   needs: []
   script:
-    - mkdir -p ./tmp
     - >
-        nix-shell --run '
-        ./scripts/build-platforms-generate.sh > ./tmp/build-platforms.yml
-        '
+      nix-shell --run '
+      ./scripts/build-platforms-generate.sh > ./tmp/build-platforms.yml
+      '
   artifacts:
     when: always
     paths:
@@ -174,24 +199,6 @@ build:platforms:
     # Runs on tag pipeline where the tag is a prerelease or release version
     - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
 
-build:dist:
-  stage: build
-  needs: []
-  script:
-    - >
-        nix-shell --run '
-        npm run build --verbose;
-        '
-  artifacts:
-    when: always
-    paths:
-      - ./dist
-  rules:
-    # Runs on staging commits and ignores version commits
-    - if: $CI_COMMIT_BRANCH == 'staging' && $CI_COMMIT_TITLE !~ /^[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
-    # Runs on tag pipeline where the tag is a prerelease or release version
-    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(?:-.*[0-9]+)?$/
-
 build:prerelease:
   stage: build
   needs:
@@ -199,14 +206,13 @@ build:prerelease:
     - build:platforms
   # Don't interrupt publishing job
   interruptible: false
-  before_script:
-    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
   script:
+    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
     - echo 'Publishing library prerelease'
     - >
-        nix-shell --run '
-        npm publish --tag prerelease --access public;
-        '
+      nix-shell --run '
+      npm publish --tag prerelease --access public;
+      '
   after_script:
     - rm -f ./.npmrc
   rules:
@@ -224,25 +230,25 @@ integration:builds:
   script:
     - mkdir -p ./builds
     - >
-        build_application="$(nix-build \
-          --max-jobs "$(nproc)" --cores "$(nproc)" \
-          ./release.nix  \
-          --attr application \
-        )"
+      build_application="$(nix-build \
+        --max-jobs "$(nproc)" --cores "$(nproc)" \
+        ./release.nix  \
+        --attr application \
+      )"
     - >
-        nix-store --export $( \
-          nix-store --query --requisites "$build_application" \
-        ) | gzip > ./builds/typescript-demo-lib.closure.gz
+      nix-store --export $( \
+        nix-store --query --requisites "$build_application" \
+      ) | gzip > ./builds/typescript-demo-lib.closure.gz
     # non-nix targets
     - >
-        builds="$(nix-build \
-          --max-jobs "$(nproc)" --cores "$(nproc)" \
-          ./release.nix \
-          --attr docker \
-          --attr package.linux.x64.elf \
-          --attr package.windows.x64.exe \
-          --attr package.macos.x64.macho \
-          --attr package.macos.arm64.macho)"
+      builds="$(nix-build \
+        --max-jobs "$(nproc)" --cores "$(nproc)" \
+        ./release.nix \
+        --attr docker \
+        --attr package.linux.x64.elf \
+        --attr package.windows.x64.exe \
+        --attr package.macos.x64.macho \
+        --attr package.macos.arm64.macho)"
     - cp -r $builds ./builds/
   artifacts:
     paths:
@@ -277,11 +283,11 @@ integration:nix:
       optional: true
   script:
     - >
-        build_application="$( \
-          gunzip -c ./builds/typescript-demo-lib.closure.gz | \
-          nix-store --import | \
-          tail -1 \
-        )"
+      build_application="$( \
+        gunzip -c ./builds/typescript-demo-lib.closure.gz | \
+        nix-store --import | \
+        tail -1 \
+      )"
     - $build_application/bin/typescript-demo-lib
   rules:
     # Runs on staging commits and ignores version commits
@@ -300,9 +306,8 @@ integration:docker:
     - docker:20.10.11-dind
   variables:
     DOCKER_TLS_CERTDIR: "/certs"
-  before_script:
-    - docker info
   script:
+    - docker info
     - image="$(docker load --input ./builds/*docker* | cut -d' ' -f3)"
     - docker run "$image"
   rules:
@@ -377,35 +382,58 @@ integration:prerelease:
       optional: true
   # Don't interrupt publishing job
   interruptible: false
+  # Requires mutual exclusion
+  resource_group: integration:prerelease
+  variables:
+    REGISTRY_AUTH_FILE: "./tmp/registry-auth-file.json"
   script:
     - echo 'Publishing application prerelease'
     - >
-        nix-shell -I nixpkgs=./pkgs.nix --packages gitAndTools.gh --run '
-        if gh release view "$CI_COMMIT_TAG" --repo "$GH_PROJECT_PATH" >/dev/null; then \
-          gh release \
-            upload "$CI_COMMIT_TAG" \
-            builds/*.closure.gz \
-            builds/*-docker-* \
-            builds/*-linux-* \
-            builds/*-win-* \
-            builds/*-macos-* \
-            --clobber \
-            --repo "$GH_PROJECT_PATH"; \
-        else \
-          gh release \
-            create "$CI_COMMIT_TAG" \
-            builds/*.closure.gz \
-            builds/*-docker-* \
-            builds/*-linux-* \
-            builds/*-win-* \
-            builds/*-macos-* \
-            --title "${CI_COMMIT_TAG}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
-            --notes "" \
-            --prerelease \
-            --target staging \
-            --repo "$GH_PROJECT_PATH"; \
-        fi;
-        '
+      nix-shell --run $'
+      set -o errexit;
+      set -o nounset;
+      set -o pipefail;
+      if gh release view "$CI_COMMIT_TAG" --repo "$GH_PROJECT_PATH" >/dev/null; then \
+        gh release \
+          upload "$CI_COMMIT_TAG" \
+          builds/*.closure.gz \
+          builds/*-docker-* \
+          builds/*-linux-* \
+          builds/*-win-* \
+          builds/*-macos-* \
+          --clobber \
+          --repo "$GH_PROJECT_PATH"; \
+      else \
+        gh release \
+          create "$CI_COMMIT_TAG" \
+          builds/*.closure.gz \
+          builds/*-docker-* \
+          builds/*-linux-* \
+          builds/*-win-* \
+          builds/*-macos-* \
+          --title "${CI_COMMIT_TAG}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
+          --notes "" \
+          --prerelease \
+          --target staging \
+          --repo "$GH_PROJECT_PATH"; \
+      fi;
+      '
+    - echo 'Prereleasing container image'
+    - >
+      nix-shell --run $'
+      set -o errexit;
+      set -o nounset;
+      set -o pipefail;
+      skopeo login \
+        --username "$CI_REGISTRY_USER" \
+        --password "$CI_REGISTRY_PASSWORD" \
+        --authfile "$REGISTRY_AUTH_FILE" \
+        "$CI_REGISTRY_IMAGE";
+      image=(./builds/*-docker-*);
+      ./scripts/deploy-image.sh "${image[0]}" \'prerelease\' "$CI_REGISTRY_IMAGE";
+      '
+  after_script:
+    - rm -f "$REGISTRY_AUTH_FILE"
   rules:
     # Only runs on tag pipeline where the tag is a prerelease version
     # This requires dependencies to also run on tag pipeline
@@ -441,12 +469,12 @@ integration:merge:
     GIT_DEPTH: 0
   script:
     - >
-        nix-shell -I nixpkgs=./pkgs.nix --packages gitAndTools.gh --run '
-        printf "Pipeline Succeeded on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
-        | gh pr comment staging \
-          --body-file - \
-          --repo "$GH_PROJECT_PATH";
-        '
+      nix-shell --run '
+      printf "Pipeline Succeeded on ${CI_PIPELINE_ID} for ${CI_COMMIT_SHA}\n\n${CI_PIPELINE_URL}" \
+      | gh pr comment staging \
+        --body-file - \
+        --repo "$GH_PROJECT_PATH";
+      '
     - git remote add upstream "$GH_PROJECT_URL"
     - git checkout origin/master
     # Merge up to the current commit (not the latest commit)
@@ -502,30 +530,45 @@ release:distribution:
     - release:deployment:tag
   # Don't interrupt publishing job
   interruptible: false
-  before_script:
-    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
+  # Requires mutual exclusion
+  resource_group: release:distribution
+  variables:
+    REGISTRY_AUTH_FILE: "./tmp/registry-auth-file.json"
   script:
+    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
     - echo 'Publishing library & application release'
     - >
-        nix-shell --run '
-        npm publish --access public;
-        '
+      nix-shell --run $'
+      npm publish --access public;
+      '
     - >
-        nix-shell -I nixpkgs=./pkgs.nix --packages gitAndTools.gh --run '
-        gh release \
-          create "$CI_COMMIT_TAG" \
-          builds/*.closure.gz \
-          builds/*-docker-* \
-          builds/*-linux-* \
-          builds/*-win-* \
-          builds/*-macos-* \
-          --title "${CI_COMMIT_TAG}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
-          --notes "" \
-          --target master \
-          --repo "$GH_PROJECT_PATH";
-        '
+      nix-shell --run $'
+      gh release \
+        create "$CI_COMMIT_TAG" \
+        builds/*.closure.gz \
+        builds/*-docker-* \
+        builds/*-linux-* \
+        builds/*-win-* \
+        builds/*-macos-* \
+        --title "${CI_COMMIT_TAG}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
+        --notes "" \
+        --target master \
+        --repo "$GH_PROJECT_PATH";
+      '
+    - echo 'Releasing container image'
+    - >
+      nix-shell --run $'
+      skopeo login \
+        --username "$CI_REGISTRY_USER" \
+        --password "$CI_REGISTRY_PASSWORD" \
+        --authfile "$REGISTRY_AUTH_FILE" \
+        "$CI_REGISTRY_IMAGE";
+      image=(./builds/*-docker-*);
+      ./scripts/deploy-image.sh "${image[0]}" \'release\' "$CI_REGISTRY_IMAGE";
+      '
   after_script:
     - rm -f ./.npmrc
+    - rm -f "$REGISTRY_AUTH_FILE"
   rules:
     # Only runs on tag pipeline where the tag is a release version
     # This requires dependencies to also run on tag pipeline
